### ISSUE TITLE
Serial Communication Error

### ISSUE THREAD

**Issue by nsiatras** [langwadt/nucleo_grbl#1]
Hello,

I just compiled the code using the System Workbench IDE. Code build is OK but after I connect to the nucleo using putty or any other serial communication software the nucleo keeps sending undifined/bulk data.

First thought was that baud rate or parity is wrong but I double checked it and this was not the issue.

Any ideas on what might be wrong ?

**Comment by langwadt** [comment]
You should use https://github.com/langwadt/grbl_stm32 instead it is the one I'm keeping updated
